apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-hftoken
spec:
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: huggingface-secret
  data:
  - secretKey: HF_TOKEN
    remoteRef:
      key: secrets/ai-kickstart
      property: hf_token